# Generated by Django 4.2.6 on 2023-10-27 06:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AppUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_of_joining", models.DateField(null=True)),
                ("is_staff", models.BooleanField()),
                ("is_hod", models.BooleanField()),
                ("mentor_username", models.CharField(max_length=30, null=True)),
                ("class_incharge_username", models.CharField(max_length=30, null=True)),
                ("HOD_username", models.CharField(max_length=30, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Form",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year_of_study",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(4),
                        ]
                    ),
                ),
                ("date_from", models.DateField()),
                ("date_to", models.DateField()),
                ("section", models.CharField(max_length=2)),
                ("student_name", models.CharField(max_length=100, null=True)),
                ("student_dept", models.CharField(max_length=30, null=True)),
                ("parent_ph_no", models.CharField(max_length=10)),
                (
                    "attendance_status",
                    models.CharField(
                        choices=[("LEAVE", "LEAVE"), ("ON DUTY", "ON DUTY")],
                        max_length=20,
                    ),
                ),
                ("is_parent_consent", models.BooleanField()),
                ("is_staff_consent", models.BooleanField()),
                ("is_HOD_consent", models.BooleanField()),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="LeaveOD.appuser",
                    ),
                ),
            ],
        ),
    ]
