# Generated by Django 4.2.4 on 2023-09-22 05:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('form_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_id', models.CharField(max_length=20)),
                ('year_of_study', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('section', models.CharField(max_length=2)),
                ('student_name', models.CharField(max_length=100, null=True)),
                ('student_dept', models.CharField(max_length=30, null=True)),
                ('parent_ph_no', models.CharField(max_length=10)),
                ('attendance_status', models.CharField(choices=[('LEAVE', 'LEAVE'), ('ON DUTY', 'ON DUTY')], max_length=20)),
                ('parent_consent', models.BooleanField()),
                ('staff_confirmation', models.BooleanField()),
                ('HOD_confirmation', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('date_of_joining', models.DateField(null=True)),
                ('is_staff', models.BooleanField()),
                ('mentor', models.CharField(max_length=30, null=True)),
                ('class_incharge', models.CharField(max_length=30, null=True)),
                ('HOD', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
