# Generated by Django 4.2.6 on 2023-10-30 10:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("LeaveOD", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="form",
            name="student",
            field=models.CharField(max_length=200),
        ),
    ]
